const entriesActionTypes = {
  GET_ENTRIES_START: "GET_ENTRIES_START",
  GET_ENTRIES_SUCCESS: "GET_ENTRIES_SUCCESS",
  GET_ENTRIES_FAILURE: "GET_ENTRIES_FAILURE",
  UPDATE_FILTER_STRING: "UPDATE_FILTER_STRING",
  ADD_ENTRY_START: "ADD_ENTRY_START",
  ADD_ENTRY_SUCCESS: "ADD_ENTRY_SUCCESS",
  ADD_ENTRY_FAILURE: "ADD_ENTRY_FAILURE",  
};

export default entriesActionTypes;