const phonebookActionTypes = {
  SET_SELECTED_PHONEBOOK: "SET_SELECTED_PHONEBOOK",
  GET_PHONEBOOKS_START: "GET_PHONE_BOOKS_START",
  GET_PHONEBOOKS_SUCCESS: "GET_PHONEBOOKS_SUCCESS",
  GET_PHONEBOOKS_FAILURE: "GET_PHONEBOOKS_FAILURE"
}

export default phonebookActionTypes;